#pragma once

namespace
	QLOGICAE_COR1__BASE__HPP_CPP__COR_NAMESPACE_NAME
{
    enum class
		EmailBody :
			QLOGICAE_COR1__BASE__HPP_CPP__ABSTRACT_ENUM_INHERITED_TYPE
    {
		HTML,

		PLAIN,

		QLOGICAE_COR1__BASE__HPP_CPP__ENUM_CONSTANTS
    };
}
