#pragma once

namespace
	QLOGICAE_COR_V1__BASE__HPP_CPP__COR_NAMESPACE_NAME
{
	enum class
		QLOGICAE_COR_V1__BASE__HPP_CPP__ABSTRACT_ENUM_NAME :
			QLOGICAE_COR_V1__BASE__HPP_CPP__ABSTRACT_ENUM_INHERITED_TYPE
	{
		QLOGICAE_COR_V1__BASE__HPP_CPP__ENUM_CONSTANTS
	};
}
